name = "OptunaDashboard"
uuid = "5594cc6f-4156-45fe-b9e0-f9dc490d6e0a"
version = "0.1.0"
authors = ["Julian Trommer <julian.trommer@uni-a.de>", "Valentin HÃ¶pfner <valentin.hoepfner@uni-a.de>", "Andreas Hofman <andreas.hofman@uni-a.de>", "Josef Kircher <josef.kircher@uni-a.de>", "Tobias Thummerer <tobias.thummerer@uni-a.de>"]

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9.31"
